services:
  - type: web
    name: guest-messenger
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
    disk:
      name: data
      mountPath: /opt/render/project/src/server
      sizeGB: 1 